### PR TITLE
Stable documentation

### PR DESCRIPTION
**Pull request by aurorarossi**

### CODE REVIEW

**Comment by CarloLucibello** [comment]
What is this doing?

**Comment by aurorarossi** [comment]
I have adjusted the workflow so that the documentation refers to the master branch. As you can see, previously the workflow was using the dev version of the package.

**Comment by CarloLucibello** [comment]
with this we loose developer docs though

**Comment by CarloLucibello** [comment]
We can close this, with #552 there has been some progress

**Pull request closed without merging**
